# lovelace_gen

type: custom:multiple-entity-row
entity: {{ entity }}
name: {{ name }}
icon: {{ icon | default('') }}
secondary_info: {{ secondary_info | default('') }}
tap_action:
  action: {{ tap_action | default('call-service') }}
  service: browser_mod.popup
  service_data:
    title: {{ name }}
    card:
      type: entities
      entities:
        - entity: {{ entity }}
          name: ' '
          icon: {{ icon | default('') }}
    deviceID:
      - this
    style:
      margin-top: -0em
      font-family: Oswald
      font-size: 14px
      border-radius: 10px
      box-shadow: 0px 0px 8px 2px
      opacity: 0.9
      "--paper-dialog-background-color": "#343433"  # Popup header
      "--paper-card-background-color": "#343433"  # Card background
style: >
  :host {
    margin-top: {{ margin_top | default ('') }};
    margin-bottom: {{ margin_bottom | default ('') }};
  }

