
#=========================
#=== TEMPERATURE SETTINGS
#=========================
type: conditional
conditions:
  - entity: input_boolean.irrigation_show_temperature_settings
    state: "on"
card:
  type: custom:stack-in-card
  cards:

    - type: entities
      entities:
        - type: divider
      style: >
        ha-card {
          margin-top: -0.5em;
          margin-bottom: -1em;
        }

    #=== Temperature Settings
    - !include
        - ../includes/titles.yaml
        - title: Temperature Settings
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== Number of days to use
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_days_of_temp_history_used
              name: Number of days data to use
              secondary_info: (0 to 4) If zero only the temperature today is used

        #=== Temperature Baseline
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_temperature_baseline
              name: Baseline temperature
              secondary_info: Exceeding this temperature increases the watering time

        - type: divider


    #=== Temperature Data
    - !include
        - ../includes/titles.yaml
        - title: Temperature Data
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== Temperature Multiplier
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_temp_multiplier
              name: Multiplier used in calculations
              secondary_info: Calculated based on temperature and baseline
              tap_action: none

        #=== Actual High Temperature
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_actual_high_temp_0
              name: High temperature today (Actual)
              tap_action: none
              margin_top: -0.5em

        #=== Forecast High Temperature
        - !include
            - item_settings_line.yaml
            - entity: sensor.dark_sky_forecast_daytime_high_temperature_0d
              name: High temperature today (Forecast)
              tap_action: none
              margin_bottom: -1em
              margin_top: -0.5em

    #=== Temperature Data
    - !include
        - ../includes/titles.yaml
        - title: Forecast vs. Actual High Temperature
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_bottom: -1.5em
          margin_left: 0.5em

    #=== Forecast vs. Actual High Temperature Graph
    - type: custom:mini-graph-card
      entities:
        - entity: sensor.dark_sky_current_temperature
          show_legend: false
        - entity: sensor.dark_sky_forecast_daytime_high_temperature_0d
          name: Outside
          show_legend: false
        - entity: binary_sensor.above_horizon
          name: Night
          y_axis: secondary
          color: black
          show_line: false
          show_points: false
          show_legend: false
      line_width: 1
      hours_to_show: 48
      points_per_hour: 4
      aggregate_func: min
      show:
        name: false
        state: false
        labels: true
        labels_secondary: false
        icon: false
      state_map:
        - value: 'on'
          label: 'Day'
        - value: 'off'
          label: 'Night'

    #=== Use Forecast High Temperature
    - type: horizontal-stack
      cards:
        - type: custom:button-card
          color-type: blank_card

        - !include
          - ../includes/button_boolean_check_box.yaml
          - entity: input_boolean.irrigation_use_forecast_high_temp
            name: Use forecast high temperature
            card_font_size: 12px

    #=== Temperature Settings
    - !include
        - ../includes/titles.yaml
        - title: Temperature History
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== High Temperature Yesterday
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_high_temp_1
              name: Yesterday
              tap_action: none

        #=== High Temperature 2 Days Ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_high_temp_2
              name: Two days ago
              tap_action: none
              margin_top: -0.5em

        #=== High Temperature 3 Days Ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_high_temp_3
              name: Three days ago
              tap_action: none
              margin_top: -0.5em

        #=== High Temperature 4 Days Ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_high_temp_4
              name: Four days ago
              tap_action: none
              margin_top: -0.5em
