
#================
#=== Automations
#================
automation:

  #===========================================================
  #=== Cycle rainfall figures for the four days before today.
  #=== Today's figure is collected at the time of calculation
  #===========================================================
  - alias: Irrigation Rainfall Cycle Data
    trigger: 
      - platform: time
        at: "00:01:00"

    action:
      - service: input_number.set_value
        entity_id: input_number.irrigation_rainfall_4
        data_template:
          value: >
            {{ states('input_number.irrigation_rainfall_3') }}

      - service: input_number.set_value
        entity_id: input_number.irrigation_rainfall_3
        data_template:
          value: >
            {{ states('input_number.irrigation_rainfall_2') }}

      - service: input_number.set_value
        entity_id: input_number.irrigation_rainfall_2
        data_template:
          value: >
            {{ states('input_number.irrigation_rainfall_1') }}

      - service: input_number.set_value
        entity_id: input_number.irrigation_rainfall_1
        data_template:
          value: >
            {{ states('sensor.smartweather_average_rain_yesterday') | int }}


  #==============================================================================
  #=== Calculate rain multiplier
  #===
  #=== This multiplier (maximum 1.00) will decrease watering time proportionally
  #=== based on the difference between the rainfall threshold and the amount of
  #=== rain over the last few days. If the threshold is reached then it will
  #=== stop watering completely.
  #===
  #=== Note that sensor.smartweather_average_rain_today is an average of several
  #=== different weather sensors reporting rainfall today for this area.
  #==============================================================================
  - alias: Irrigation Rainfall Calculate Multiplier
    trigger:
      - platform: state
        entity_id: 
          - input_number.irrigation_days_of_rainfall_history_used
          - sensor.smartweather_average_rain_today
          - input_number.irrigation_rainfall_threshold
          - input_number.irrigation_rainfall_percentage_1
          - input_number.irrigation_rainfall_percentage_2
          - input_number.irrigation_rainfall_percentage_3
          - input_number.irrigation_rainfall_percentage_4

      - platform: state
        entity_id:
          - input_boolean.irrigation_cycle1_adjust_for_rainfall
          - input_boolean.irrigation_cycle2_adjust_for_rainfall
        to: 'on'

    action:
      - service: input_number.set_value
        data_template:
          entity_id: input_number.irrigation_rainfall_multiplier
          value: >
            {% set rain_0 = states('sensor.smartweather_average_rain_today') | float %}
            {% set rain_1 = states('input_number.irrigation_rainfall_1')  | float%}
            {% set rain_2 = states('input_number.irrigation_rainfall_2')  | float%}
            {% set rain_3 = states('input_number.irrigation_rainfall_3')  | float%}
            {% set rain_4 = states('input_number.irrigation_rainfall_4')  | float%}

            {% set percent_1 = states('input_number.irrigation_rainfall_percentage_1') | float / 100 %}
            {% set percent_2 = states('input_number.irrigation_rainfall_percentage_2') | float / 100 %}
            {% set percent_3 = states('input_number.irrigation_rainfall_percentage_3') | float / 100 %}
            {% set percent_4 = states('input_number.irrigation_rainfall_percentage_4') | float / 100 %}
            
            {% set rain_1 = rain_1 * percent_1 %}
            {% set rain_2 = rain_2 * percent_2 %}
            {% set rain_3 = rain_3 * percent_3 %}
            {% set rain_4 = rain_4 * percent_4 %}

            {% set days_used = states('input_number.irrigation_days_of_rainfall_history_used') | int %}
            {% set threshold = states('input_number.irrigation_rainfall_threshold') | int %}

            {% set rain_total = rain_0 %}
            {% if days_used == 1 %}
              {% set rain_total = rain_total + rain_1 %}
            {% endif %}
            {% if days_used == 2 %}
              {% set rain_total = rain_total + rain_2 %}
            {% endif %}
            {% if days_used == 3 %}
              {% set rain_total = rain_total + rain_3 %}
            {% endif %}
            {% if days_used == 4 %}
              {% set rain_total = rain_total + rain_4 %}
            {% endif %}

            {% set multiplier = (1 - (rain_total / threshold)) | round(2) %}
            {% if multiplier <= 0 %}
              {% set multiplier = 0 %}
            {% endif %}

            {% if rain_total >= threshold %}
              0
            {% else %}
              {{ multiplier }}
            {% endif %}

